export const types = {
	LOGIN_START: 'LOGIN_START',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT: 'LOGOUT',
	UPDATE_START: 'UPDATE_START',
	UPDATE_SUCCESS: 'UPDATE_SUCCESS',
	UPDATE_FAILURE: 'UPDATE_FAILURE',
};
